-- MySQL Script generated by MySQL Workbench
-- Fri Dec 15 15:51:49 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EventosESCOM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EventosESCOM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EventosESCOM` DEFAULT CHARACTER SET utf8 ;
USE `EventosESCOM` ;

-- -----------------------------------------------------
-- Table `EventosESCOM`.`Sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosESCOM`.`Sede` (
  `IdSede` INT NOT NULL AUTO_INCREMENT,
  `Sede` VARCHAR(45) NOT NULL,
  `Domicilio` VARCHAR(60) NOT NULL,
  `Capacidad` INT NOT NULL,
  PRIMARY KEY (`IdSede`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosESCOM`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosESCOM`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `PrimerApellido` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(15) NULL,
  `EstatusAdministrador` TINYINT NOT NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosESCOM`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosESCOM`.`Evento` (
  `Evento` VARCHAR(10) NOT NULL,
  `Periodo` VARCHAR(10) NOT NULL,
  `Fecha` DATE NULL,
  `Hora` TIME(5) NULL,
  `IdSede` INT NOT NULL,
  `idAdministrador` INT NOT NULL,
  PRIMARY KEY (`Evento`, `Periodo`),
  INDEX `fk_Evento_Sede_idx` (`IdSede` ASC),
  INDEX `fk_Evento_Administrador1_idx` (`idAdministrador` ASC),
  CONSTRAINT `fk_Evento_Sede`
    FOREIGN KEY (`IdSede`)
    REFERENCES `EventosESCOM`.`Sede` (`IdSede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_Administrador1`
    FOREIGN KEY (`idAdministrador`)
    REFERENCES `EventosESCOM`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosESCOM`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosESCOM`.`Alumno` (
  `Boleta` INT NOT NULL,
  `Nombre` VARCHAR(50) NULL,
  `PeriodoIngreso` VARCHAR(20) NULL,
  `Carrera` VARCHAR(45) NULL,
  `Plan` VARCHAR(20) NULL,
  `Especialidad` VARCHAR(45) NULL,
  `Semestre` VARCHAR(45) NULL,
  `Inscrito` TINYINT NULL,
  `TotalCreditos` FLOAT NULL,
  `MateriaReprobadas` INT NULL,
  `MateriasAcreditadas` INT NULL,
  `CreditosInscritos` FLOAT NULL,
  `MateriasInscritas` INT NULL,
  `Promedio` FLOAT NULL,
  `CURP` VARCHAR(45) NULL,
  `Turno` VARCHAR(45) NULL,
  `Genero` VARCHAR(15) NULL,
  `Edad` INT NULL,
  `Fecnacimiento` DATE NULL,
  `TelFijo` INT NULL,
  `TelMovil` INT NULL,
  `Correo` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(20) NOT NULL,
  `ActivaSesion` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Boleta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosESCOM`.`AlumnoGeneracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosESCOM`.`AlumnoGeneracion` (
  `Boleta` INT NOT NULL,
  `EstadoFoto` TINYINT NOT NULL,
  `Observacion` MEDIUMTEXT NULL,
  INDEX `fk_AlumnoGeneracion_Alumno1_idx` (`Boleta` ASC),
  CONSTRAINT `fk_AlumnoGeneracion_Alumno1`
    FOREIGN KEY (`Boleta`)
    REFERENCES `EventosESCOM`.`Alumno` (`Boleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosESCOM`.`AlumnoEvento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosESCOM`.`AlumnoEvento` (
  `Evento` VARCHAR(10) NOT NULL,
  `Periodo` VARCHAR(10) NOT NULL,
  `Boleta` INT NOT NULL,
  `Asistencia` TINYINT NOT NULL,
  PRIMARY KEY (`Evento`, `Periodo`, `Boleta`),
  INDEX `fk_Evento_has_Alumno_Alumno1_idx` (`Boleta` ASC),
  INDEX `fk_Evento_has_Alumno_Evento1_idx` (`Evento` ASC, `Periodo` ASC),
  CONSTRAINT `fk_Evento_has_Alumno_Evento1`
    FOREIGN KEY (`Evento` , `Periodo`)
    REFERENCES `EventosESCOM`.`Evento` (`Evento` , `Periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_has_Alumno_Alumno1`
    FOREIGN KEY (`Boleta`)
    REFERENCES `EventosESCOM`.`Alumno` (`Boleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosESCOM`.`AlumnoExelencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosESCOM`.`AlumnoExelencia` (
  `Boleta` INT NOT NULL,
  INDEX `fk_AlumnoGeneracion_Alumno1_idx` (`Boleta` ASC),
  CONSTRAINT `fk_AlumnoGeneracion_Alumno10`
    FOREIGN KEY (`Boleta`)
    REFERENCES `EventosESCOM`.`Alumno` (`Boleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
